wuwentao/midea_ac_lan

custom_components/midea_ac_lan/midea/core/cloud.py
Handle `TypeError` when `modelNumber` is None
=> fix: TypeError when modelNumber is None

custom_components/midea_ac_lan/midea_devices.py
Suggestion: Zone 2 should perhaps be optional as this is not active with every heat pump.
=> Suggestion: Zone 2 should perhaps be optional

hacs.json
2022.5 was the previously required version. IDK why it was updated to 2024.4. Is there something that only works on 2024.4?
fix #24
=> chore(hacs): revert required homeassistant version

custom_components/midea_ac_lan/midea/devices/c3/message.py
Fix: Midea heat pump outside temperature issue when below zero https://github.com/georgezhao2010/midea_ac_lan/issues/427
=> Fix: Midea heat pump outside temperature issue when below zero

custom_components/midea_ac_lan/config_flow.py
fix: Error: Flow handler not found for entry xxxx for midea_ac_lan
https://github.com/wuwentao/midea_ac_lan/commit/8f24cadc522e4213456cf6c287353f4c8b53ea48#diff-f5d8707f0a5c6f23f230428526ed086afb1199041d6b903c248e5e44bbca42d5L73
=> fix: Flow handler not found for entry xxxx for midea_ac_lan

.github/workflows/linter.yml
1. lint will rerun after PR merged to master, it will caused pre-commit error,  disable push check before it can works.
2. upgrade setup-python to new version as warning msg in github action:
`Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/setup-python@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.`
fix #X
=> fix lint error after PR merged to master

.github/workflows/linter.yml
Disable `black` to avoid conflicts with `ruff` that is enable as a pre-commit hook.
=> build: disable black

custom_components/midea_ac_lan/climate.py
=> chore: climate typing

custom_components/midea_ac_lan/config_flow.py
=> chore: config_flow typing

custom_components/midea_ac_lan/climate.py
`zone` should be 0 or 1
https://github.com/wuwentao/midea_ac_lan/blob/27a5047c41fbc0416991ce0dc2940ce3f42c491e/custom_components/midea_ac_lan/midea_devices.py#L871
https://github.com/wuwentao/midea_ac_lan/blob/27a5047c41fbc0416991ce0dc2940ce3f42c491e/custom_components/midea_ac_lan/midea_devices.py#L878
---
`current_temperature` can return `None`, don't change its behavior yet.
=> fix: revert some changes from #53

custom_components/midea_ac_lan/humidifier.py
#50 removed property `min_humidity` and `max_humidity`, which make `self._min_humidity` and `self._max_humidity` meaningless.
so change it using `_attr_*` attributes
=> fix: use `_attr_*` attributes

custom_components/midea_ac_lan/fan.py
as #63 description 
```
File "/config/custom_components/midea_ac_lan/fan.py", line 159, in is_on
return self.state == STATE_ON
```
`RecursionError: maximum recursion depth exceeded`
checked with commit history, should be introduced with mypy changes:
https://github.com/wuwentao/midea_ac_lan/commit/e804cd251a67c22480c7940c0330e9581061e68b
is_on return bool
use the same method as base class MideaFan.is_on
and  set the value with `fresh_air_power` from the commit history
fix #63
=> fix: fan is_on error and maximum recursion error log consumed all disk space

.pre-commit-config.yaml
pre-commit codespell can't works for de.json
seems only one json file can't works now, just ignore this file in pre-commit config.
#60 PR can't pass pre-commit codespell, it should be an error.
just ignore this file
fix #X
=> fix: exclude de.json for pre-commit codespell check

custom_components/midea_ac_lan/__init__.py
`hass.config_entries.async_forward_entry_setups` must always be awaited
https://developers.home-assistant.io/blog/2024/06/12/async_forward_entry_setups
https://developers.home-assistant.io/blog/2022/07/08/config_entry_forwards/
=> awaiting `async_forward_entry_setups`

custom_components/midea_ac_lan/manifest.json
Bump upstream library to 1.0.5:
changelog: https://github.com/rokam/midea-local/releases/tag/v1.0.5
diff: https://github.com/rokam/midea-local/compare/v1.0.3...v1.0.5
NOTE: Please test both already registered devices and new device registration before releasing a new component version
=> feat: bump midea_local to 1.0.5

custom_components/midea_ac_lan/midea_entity.py
The correct typing of the line of code needs a migration of the identifier that currently is wrongly stored as a integer.
For this reason we temporary revert the code to the previous behaviour, so to make a new fully working release and test all the other changes.
=> fix: temporary revert typing

custom_components/midea_ac_lan/__init__.py
```
2024-06-20 12:15:04.249 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry 客厅空调 for midea_ac_lan
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
result = await component.async_setup_entry(hass, self)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/midea_ac_lan/__init__.py", line 191, in async_setup_entry
customize: str = config_entry.options[CONF_CUSTOMIZE]
~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: 'customize'
```
update 
`
customize: str = config_entry.options[CONF_CUSTOMIZE] 
`
to :
`
customize: str = config_entry.options.get(CONF_CUSTOMIZE, "")
`
fix #X
=> fix: access customize dict key error when default is None

custom_components/midea_ac_lan/__init__.py, custom_components/midea_ac_lan/config_flow.py, custom_components/midea_ac_lan/midea_entity.py
Fixing device registry because of a faulty value: device id was wrongly stored as a int.
Old:    `"identifiers":[["midea_ac_lan",146235046630005]]`
New:  `"identifiers":[["midea_ac_lan","146235046630005"]]`
=> fix: migrate identifier

.devcontainer/Dockerfile, .devcontainer/devcontainer.json
we have installed both python3.12 in devcontainer
our `Dockerfile` base image is `python3.12`, and the base os already have builtin `python3.12`,  and install all the requirements via our local repo `requirement-all-xxx.txt` file.
but `devcontainer.json` still installed a duplicate `python3.12` to the base os and caused default python3 and pip can't work.
just remove it and keep only one python3.12.
fix #X
=> fix: remove duplicate python3.12 in devcontainer

custom_components/midea_ac_lan/config_flow.py
```
2024-06-25 14:59:01.473 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
resp = await request_handler(request)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/aiohttp/web_app.py", line 543, in _handle
resp = await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/aiohttp/web_middlewares.py", line 114, in impl
return await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 92, in security_filter_middleware
return await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File …
```
=> fix: convert int device_id to str

custom_components/midea_ac_lan/midea_devices.py, custom_components/midea_ac_lan/midea_entity.py, custom_components/midea_ac_lan/translations/de.json, custom_components/midea_ac_lan/translations/en.json, custom_components/midea_ac_lan/translations/fr.json, custom_components/midea_ac_lan/translations/hu.json, custom_components/midea_ac_lan/translations/ru.json, custom_components/midea_ac_lan/translations/sk.json, custom_components/midea_ac_lan/translations/zh-Hans.json
This PR introduces the new way of [entity naming](https://developers.home-assistant.io/docs/core/entity/#entity-naming).
> Avoid setting an entity's name to a hard coded English string, instead, the name should be [translated](https://developers.home-assistant.io/docs/internationalization/core#name-of-entities).
Here gives an example of `ED` device in `en` and `zh-Hans` (other languages simply copy `en`),
for a smooth migration, manually set `"has_entity_name": True` to use the new naming method, otherwise keep the original behavior.
`translation_key` can be `None`, which represents [the **main feature** of a device](https://developers.home-assistant.io/docs/core/entity/#example-of-a-switch-entity-which-is-the-main-feature-of-a-device).
Fully entity naming will be a huge task or may be …
=> feat: new entity naming

requirements-dev-3.11.txt, requirements-dev-3.12.txt, requirements-dev.txt
Missing requirements are needed to allow VScode debugging
=> build:  cleanup  requirements and add missing ones

.vscode/launch.json, requirements-dev.txt
Please select "**Dev Containers: Rebuild Container Without Cache**"  from VScode command palette when rebuilding the devcontainer.
=> fix: VScode debugging part2

.pre-commit-config.yaml, custom_components/midea_ac_lan/config_flow.py, pylintrc, requirements-dev.txt
Enable `pylint` only for **Errors** and **Fatal** categories.
This will help prevent issues like the following:
=> build: enable pylint Error and Fatal rules

custom_components/midea_ac_lan/manifest.json, requirements.txt
midealocal v1.3.0 only used for mainfest v0.5.1 new release, to fix urgent error, so directly update this file with both version content, not split to both PRs with more steps.
I think it should be acceptable, please help to review, then we can quickly release new version.
fix #215 , #221 , #207 ,  #191
=> chore: bump midealocal v1.3.0

custom_components/midea_ac_lan/config_flow.py
Device connect was called in a mock device when it shouldn't.
It should fix raise of get capabilities on flow and get_keys.
fixes #221 #219
=> fix(flow): get capabilities should not happen during flow

custom_components/midea_ac_lan/config_flow.py
If a user choose discovery and uses a broadcast ip or auto, multiple devices are retrieved.
When moved to manual step, the user might receive and error that the device_id should be other (the first on the discover list). 
With wrong device_id,  authentication will fail.
With this change, it'll use the devices only if no discover where made.
=> fix(config_flow): when using auto, wrong device_id might be used

custom_components/midea_ac_lan/midea_devices.py, custom_components/midea_ac_lan/midea_entity.py, custom_components/midea_ac_lan/translations/de.json, custom_components/midea_ac_lan/translations/en.json, custom_components/midea_ac_lan/translations/fr.json, custom_components/midea_ac_lan/translations/hu.json, custom_components/midea_ac_lan/translations/ru.json, custom_components/midea_ac_lan/translations/sk.json, custom_components/midea_ac_lan/translations/zh-Hans.json
- Fix the naming of a device **main** feature, use `"has_entity_name": True` and `"name": None`
- Add some entity name to `40` device
The previous implementation had some problems.
#174
=> fix: main feature entity name

custom_components/midea_ac_lan/manifest.json
Add missing logger to the manifest so when debugging is enabled from the UI is enabled also for the library and not only for the integration.
=> fix: add missing logger

custom_components/midea_ac_lan/config_flow.py
the should be an error process for device authenticate
=> fix: only protocol v3 device should run authenticate in config_flow

custom_components/midea_ac_lan/water_heater.py
do the same thing as #66 for E2 devices.
#59
=> fix: state of water heater E2

custom_components/midea_ac_lan/fan.py
SSIA
https://developers.home-assistant.io/blog/2024/07/19/fan-fanentityfeatures-turn-on_off/
from the current HA (2024.8.2) logs
```log
2024-08-16 20:31:49.478 WARNING (MainThread) [homeassistant.components.fan] Entity midea_ac_lan.153931628304529_fresh_air (<class 'custom_components.midea_ac_lan.fan.MideaACFreshAirFan'>) does not set FanEntityFeature.TURN_OFF but implements the turn_off method. Please create a bug report at https://github.com/wuwentao/midea_ac_lan/issues
2024-08-16 20:31:49.478 WARNING (MainThread) [homeassistant.components.fan] Entity midea_ac_lan.153931628304529_fresh_air (<class 'custom_components.midea_ac_lan.fan.MideaACFreshAirFan'>) does not set FanEntityFeature.TURN_ON but implements the turn_on method. Please create a bug report at …
```
=> fix: Add MideaACFreshAirFan feature turn_on and turn_off

custom_components/midea_ac_lan/water_heater.py
these values are for target temperature range. It is obviously incorrect to set these values to min_temp and max_temp. Since we can not get/set the device's target temperature range, we should not set these values.
=> fix: water_heater: do not set target_temperature_high and target_temperature_low

custom_components/midea_ac_lan/manifest.json, requirements.txt
`pycryptodome` is needed by the library, not the integration
=> build: cleanup requirements

custom_components/midea_ac_lan/climate.py
AC device temperature range should be 16-30 and not 17-30
fix #396
=> fix(ac): update AC device min temperature from 17 to 16

custom_components/midea_ac_lan/climate.py
Support `current_humidity` for `climate`
=> feat(AC): support `current_humidity` for  AC device `climate`

README.md, README_hans.md
1. add upgrade steps
2. add QQ group
fix #437
=> chore(readme): add upgrade steps and QQ group in readme

custom_components/midea_ac_lan/light.py
replace ATTR_COLOR_TEMP with ATTR_COLOR_TEMP_KELVIN 
follow https://developers.home-assistant.io/blog/2024/12/14/kelvin-preferred-color-temperature-unit
HA deprecated constant ATTR_COLOR_TEMP
fix #435
=> fix(light): replace ATTR_COLOR_TEMP with ATTR_COLOR_TEMP_KELVIN 

custom_components/midea_ac_lan/manifest.json, requirements.txt
bump midea-local to v6.1.0
bump midea-local to v6.1.0
fix #X
=> chore(main): bump midea-local to v6.1.0

requirements-dev.txt
switch mypy-dev to mypy release as dev version not available now
switch mypy-dev to mypy release as dev version not available now
```
Collecting ffmpeg==1.4 (from -r /home/runner/work/midea_ac_lan/midea_ac_lan/requirements-dev.txt (line 2))
Downloading ffmpeg-1.4.tar.gz (5.1 kB)
Installing build dependencies: started
Installing build dependencies: finished with status 'done'
Getting requirements to build wheel: started
Getting requirements to build wheel: finished with status 'done'
Preparing metadata (pyproject.toml): started
Preparing metadata (pyproject.toml): finished with status 'done'
ERROR: Could not find a version that satisfies the requirement mypy-dev==1.11.0a6 (from versions: 1.9.0b1, 1.10.0b1, 1.11.0b1, 1.12.0b1, 1.13.0a2, 1.14.0a1, 1.14.0a2, 1.14.0a3, 1.14.0a4, 1.14.0a5, …
```
=> chore(mypy): switch mypy-dev to mypy release

custom_components/midea_ac_lan/config_flow.py
as SmartHome closed the token api service, switch to NetHome Plus
=> fix(cloud): switch default cloud from SmartHome to NetHome Plus

custom_components/midea_ac_lan/midea_devices.py, custom_components/midea_ac_lan/translations/en.json, custom_components/midea_ac_lan/translations/zh-Hans.json
fix ac device custom fan_mode value translate
define climate with a translate_key `climate_key` and add translate file to support it.
fix #483
=> fix(ac): fix ac device custom fan_mode value translate
