README.md
README_hans.md

Changed url in readme to point to @wuwentao

Changed url to point to @wuwentao repo

---

.vscode/launch.json
scripts/setup.sh

Add launch config to VSCode

---

.devcontainer/devcontainer.json

Adjust black configuration at devcontainer
Add the black configuration with extension and removed from legacy place

Adjust black configuration at devcontainer

---

.github/workflows/release.yml

release script retunr permission error
add sudo to fix it

FIx: release script permission error

---

custom_components/midea_ac_lan/__init__.py

chore: typing __init__

---

custom_components/midea_ac_lan/config_flow.py

fix: TypeError: 'int' object is not subscriptable
https://github.com/wuwentao/midea_ac_lan/commit/8f24cadc522e4213456cf6c287353f4c8b53ea48#diff-f5d8707f0a5c6f23f230428526ed086afb1199041d6b903c248e5e44bbca42d5R85

fix: TypeError: 'int' object is not subscriptable

---

custom_components/midea_ac_lan/__init__.py

fix old versions compatibility
`hass.async_add_import_executor_job` was introduced in HA 2024.3

fix old versions compatibility

---

.github/workflows/linter.yml
.pre-commit-config.yaml
custom_components/midea_ac_lan/climate.py
custom_components/midea_ac_lan/config_flow.py
custom_components/midea_ac_lan/light.py
custom_components/midea_ac_lan/lock.py
requirements.dev.txt
requirements.txt
scripts/setup.sh

build: enable pre-commit

---

custom_components/midea_ac_lan/binary_sensor.py

chore: typing binary_sensor

---

custom_components/midea_ac_lan/number.py
custom_components/midea_ac_lan/select.py
custom_components/midea_ac_lan/sensor.py
custom_components/midea_ac_lan/switch.py

- number
- select
- sensor
- switch

chore: more typing

---

custom_components/midea_ac_lan/__init__.py

just found this error , and quickly fix it.
it should be `key or token`, not `key or key`, should be an input error

chore: input error with if condition

---

custom_components/midea_ac_lan/humidifier.py

chore: type humidifier

---

custom_components/midea_ac_lan/water_heater.py

chore: water_heater typing

---

custom_components/midea_ac_lan/fan.py

chore: typing fan

---

custom_components/midea_ac_lan/fan.py

chore: add missing typing to fan

---

mypy.ini

Drafting this PR to allow all Team members to be on the same page.
Will be enabled once code base will be compliant.

chore: enable mypy final rules

---

custom_components/midea_ac_lan/manifest.json

I do propose a new release to guarantee the same version in the release and manifest
Some issues are reported as a wrong version.

chore(manifest): wrong version

---

.github/workflows/release.yml

add release version check with manifest.json verion

fix: add release version check with manifest.json verion

---

custom_components/midea_ac_lan/water_heater.py

#51 simply removed property `state` is not a safe operation
fix #59

fix: state of water heater C3 and E6

---

custom_components/midea_ac_lan/climate.py
custom_components/midea_ac_lan/fan.py
custom_components/midea_ac_lan/humidifier.py
custom_components/midea_ac_lan/midea_entity.py
custom_components/midea_ac_lan/number.py
custom_components/midea_ac_lan/select.py
custom_components/midea_ac_lan/water_heater.py

Add typing for `self._device`

---

custom_components/midea_ac_lan/__init__.py
custom_components/midea_ac_lan/config_flow.py

1. add detail process and comments for `__init__.py` and `config_flow.py`
2. user can quickly understand  the process and what it did,  they can easy to help us in open source project
3. also update some old syntax with new syntax
fix #X

chore: add detail comments for init and config_flow

---

custom_components/midea_ac_lan/climate.py

- Move some property to `_attr_*` attributes
- Changed `fan_modes` of `MideaACClimate` to constants from HA
- `fan_modes` of `MideaCCClimate` will be fixed by lib later
- Translations for "silent" and "full" may be added later
fix #71

improve `climate.py` and change fan modes to constants from HA

---

custom_components/midea_ac_lan/config_flow.py
custom_components/midea_ac_lan/midea_entity.py

keep compatibility with HA 2023.1
fix #74

keep compatibility with HA 2023.1

---

custom_components/midea_ac_lan/humidifier.py

Support `current_humidity` for `humidifier`
fix #23

Support `current_humidity` for `humidifier`

---

.github/dependabot.yml

build: enable dependabot

---

custom_components/midea_ac_lan/binary_sensor.py
custom_components/midea_ac_lan/climate.py
custom_components/midea_ac_lan/config_flow.py
custom_components/midea_ac_lan/fan.py
custom_components/midea_ac_lan/humidifier.py
custom_components/midea_ac_lan/light.py
custom_components/midea_ac_lan/lock.py
custom_components/midea_ac_lan/number.py
custom_components/midea_ac_lan/select.py
custom_components/midea_ac_lan/sensor.py
custom_components/midea_ac_lan/switch.py
custom_components/midea_ac_lan/water_heater.py

chore: ruff autofix

---

custom_components/midea_ac_lan/climate.py
custom_components/midea_ac_lan/water_heater.py

chore: partial fix rufff RUF012

---

custom_components/midea_ac_lan/climate.py
custom_components/midea_ac_lan/config_flow.py
custom_components/midea_ac_lan/water_heater.py

chore: fix ruff RET505

---

custom_components/midea_ac_lan/manifest.json
hacs.json
requirements.txt

bump midea_local to 1.1.0

---

custom_components/midea_ac_lan/climate.py
custom_components/midea_ac_lan/fan.py
custom_components/midea_ac_lan/humidifier.py
custom_components/midea_ac_lan/light.py
custom_components/midea_ac_lan/midea_entity.py
custom_components/midea_ac_lan/number.py
custom_components/midea_ac_lan/select.py
custom_components/midea_ac_lan/water_heater.py

chore: fix ruff D107

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json

fix vscode clone repo with volume error in build docker
fix #X

fix: dockerfile args miss error

---

custom_components/midea_ac_lan/water_heater.py

chore: fix ruff D102 for water_heater.py

---

custom_components/midea_ac_lan/climate.py
custom_components/midea_ac_lan/fan.py
custom_components/midea_ac_lan/humidifier.py
custom_components/midea_ac_lan/light.py
custom_components/midea_ac_lan/water_heater.py

chore: fix ruff d103

---

custom_components/midea_ac_lan/climate.py
custom_components/midea_ac_lan/fan.py
custom_components/midea_ac_lan/humidifier.py
custom_components/midea_ac_lan/light.py
custom_components/midea_ac_lan/water_heater.py

chore: fix ruff d101

---

custom_components/midea_ac_lan/humidifier.py

chore: fix ruff d102 for humidifier.py

---

custom_components/midea_ac_lan/fan.py

chore: fix ruff d102 for fan.py
fix #X

chore: fix ruff d102 for fan.py

---

custom_components/midea_ac_lan/climate.py

chore: fix ruff d102 for climate.py
fix #X

chore: fix ruff d102 for climate.py

---

custom_components/midea_ac_lan/light.py

chore: fix ruff d102 for light.py
fix #X

chore: fix ruff d102 for light.py

---

custom_components/midea_ac_lan/config_flow.py

https://github.com/wuwentao/midea_ac_lan/pull/109#discussion_r1650061147

fix: compatibility with python 3.11

---

.pre-commit-config.yaml

Prerequisite to enable again [pre-commit.ci](https://pre-commit.ci/)

build(pre-commit.ci): disable local hooks

---

.devcontainer/Dockerfile

fix: remove duplicate mypy in devcontainer

---

custom_components/midea_ac_lan/climate.py

fix: fan_mode should return str type

---

custom_components/midea_ac_lan/climate.py

Fix the reference to hvac_modes list.
fix #196

fix(c3): correct reference

---

custom_components/midea_ac_lan/config_flow.py

When the user don't provice key and token for v3 devices, it could retrieve keys from default MSmart account. This will avoid user error or lack of cloud account.
fix #185

feat(v3): retrieve keys from preset account if not informed

---

.github/ISSUE_TEMPLATE/1-issue_zh-cn.yml
.github/ISSUE_TEMPLATE/2-issue_en.yml

chore: update issue description for debug log info

---

custom_components/midea_ac_lan/config_flow.py

fix: save device config

---

custom_components/midea_ac_lan/manifest.json
requirements.txt

chore: bump 1.2.0

---

custom_components/midea_ac_lan/manifest.json

chore: bump manifest

---

.github/linters/.eslintrc.yml
.github/linters/.flake8
.github/linters/.python-lint
.github/linters/.yaml-lint.yml

Follow up of #164 (remove superlinter)

build: cleanup unused config

---

custom_components/midea_ac_lan/manifest.json

update mainfest.json version to publish new release
fix #X

chore: update mainfest.json to publish v0.5.1 release

---

custom_components/midea_ac_lan/manifest.json
requirements.txt

chore: bump lib version

---

.github/ISSUE_TEMPLATE/1-issue_zh-cn.yml
.github/ISSUE_TEMPLATE/2-issue_en.yml

Please add Chinese before merging

chore(issue_template): better wording

---

custom_components/midea_ac_lan/manifest.json
requirements.txt

Fix Refresh capabilities is timed out
fix #X

chore: bump midea-local to v1.3.2 and fix Refresh capabilities is timed out

---

custom_components/midea_ac_lan/manifest.json

chore: update mainfest version to v0.5.3 and fix refresh timeout

---

custom_components/midea_ac_lan/config_flow.py
custom_components/midea_ac_lan/manifest.json
requirements.txt

chore(lib): bump version

---

.github/workflows/issue-open.yml

Opens issue at library repo if labeled as `midea-local library`

chore(ci): open issue at lib repo

---

.github/workflows/issue-open.yml

We need a token that can open issues in midea-local repository
fix #X

chore: use correct token to open issue

---

custom_components/midea_ac_lan/config_flow.py
custom_components/midea_ac_lan/manifest.json
requirements.txt

chore: bump lib 2.6.0

---

custom_components/midea_ac_lan/manifest.json

update mainfest.json to bump new release with v0.5.5
fix #X

chore: bump version 0.5.5

---

custom_components/midea_ac_lan/manifest.json
requirements.txt

chore(lib): bump version 2.6.2

---

custom_components/midea_ac_lan/midea_devices.py

feat(c3): silent level

---

custom_components/midea_ac_lan/manifest.json

chore: bump version 0.5.6

---

custom_components/midea_ac_lan/manifest.json

bump new version to fix config_flow bug
fix #X

chore: bump version 0.5.7

---

custom_components/midea_ac_lan/translations/de.json

German translation update

---

custom_components/midea_ac_lan/translations/de.json

German translation update 2

---

custom_components/midea_ac_lan/__init__.py

https://github.com/wuwentao/midea_ac_lan/pull/268#discussion_r1739964624

fix: `async_setup` should return `bool`

---

custom_components/midea_ac_lan/diagnostics.py

feat: add diagnostics

---

custom_components/midea_ac_lan/__init__.py

chore: add missing typing

---

custom_components/midea_ac_lan/manifest.json
requirements.txt

bump midealocal to v3.0.0
fix socket exception issue
fix #X

chore(lib): bump midea-local to v3.0.0

---

custom_components/midea_ac_lan/manifest.json

publish release version v0.5.8
fix socket exception issue
fix #X

chore: bump version v0.5.8

---

custom_components/midea_ac_lan/manifest.json
requirements.txt

fix high cpu usage with midea-local v3.0.1
fix #X

chore(lib): fix high cpu usage with midea-local v3.0.1

---

custom_components/midea_ac_lan/manifest.json
requirements.txt

publish v0.5.9 to fix high cpu issue
fix #315

chore: bump version v0.5.9

---

custom_components/midea_ac_lan/manifest.json
requirements.txt

fix #333 #331 #328 #327 #323 #321 #319

chore: bump version v0.6.0

---

custom_components/midea_ac_lan/translations/zh-Hans.json

add zh-Hans language translate for all the entry
fix #342

chore: add zh-Hans language  translate

---

custom_components/midea_ac_lan/config_flow.py

fix: config flow protocol default

---

.devcontainer/Dockerfile
.pre-commit-config.yaml
commitlint.config.mjs
scripts/setup.sh

Sync local pre-commit behaviour with CI:

build: add commitlint to pre-commit

---

custom_components/midea_ac_lan/config_flow.py

Follow up of #354 where unfortunately I patched the wrong line.
fix #359

fix: protocol select in config_flow

---

.github/workflows/issue-open.yml

Open the issue at midea-lan/midea-local

chore: open issue

---

doc/debug.md
doc/debug_hans.md

add debug and test docs
fix #X

chore(doc): add debug and test docs

---

doc/C3.md
doc/C3_hans.md

feature should be add in https://github.com/wuwentao/midea_ac_lan/pull/273
but it missed docs update, add these missed docs.

chore(docs): add C3 device silent level docs

---

custom_components/midea_ac_lan/manifest.json

chore(main): bump version v0.6.6

---

doc/debug.md
doc/debug_hans.md

add get device type and sn in debug doc
for debug purpose
fix #X

chore(doc): add get device type and sn in debug doc

---

.github/ISSUE_TEMPLATE/1-issue_zh-cn.yml
.github/ISSUE_TEMPLATE/2-issue_en.yml
.github/ISSUE_TEMPLATE/3-enhancement_zh-cn.yml
.github/ISSUE_TEMPLATE/4-enhancement_en.yml

add debug log as mandatory info in all issue template
add debug log as mandatory info in all issue template
fix #X

chore(main): add debug log as mandatory info in all issue template

---

custom_components/midea_ac_lan/midea_devices.py
custom_components/midea_ac_lan/translations/de.json
custom_components/midea_ac_lan/translations/en.json
custom_components/midea_ac_lan/translations/fr.json
custom_components/midea_ac_lan/translations/hu.json
custom_components/midea_ac_lan/translations/ru.json
custom_components/midea_ac_lan/translations/sk.json
custom_components/midea_ac_lan/translations/zh-Hans.json
doc/CD.md
doc/CD_hans.md

add 0xCD device water level attr and docs
fix #425

feat(cd): add 0xCD device water level attr and docs

---

custom_components/midea_ac_lan/manifest.json
requirements.txt

bump midea-local to v6.2.0
fix #X

chore(main): bump midea-local to v6.2.0

---

.pre-commit-config.yaml
README.md
README_hans.md
custom_components/midea_ac_lan/midea_devices.py
doc/AD.md
doc/AD_hans.md

feat(ad): add 0xAD device attrs

---

custom_components/midea_ac_lan/manifest.json

midea_ac_lan release v0.6.7
fix #X

chore(main): midea_ac_lan release v0.6.7

---

custom_components/midea_ac_lan/manifest.json
requirements.txt

chore(main): bump midea-local to v6.3.0

---

custom_components/midea_ac_lan/manifest.json
hacs.json

chore(main): midea_ac_lan release v0.6.8

---

doc/E2.md
doc/E2_hans.md

add precision_halves to E2 device doc
fix #X

feat(doc): update E2 device doc for precision_halves

---

.github/ISSUE_TEMPLATE/1-issue_zh-cn.yml
.github/ISSUE_TEMPLATE/2-issue_en.yml
.github/ISSUE_TEMPLATE/3-enhancement_zh-cn.yml
.github/ISSUE_TEMPLATE/4-enhancement_en.yml

chore: update issue template with checkboxes

---

custom_components/midea_ac_lan/manifest.json

chore(main): midea_ac_lan release v0.6.9

---

.github/.pr_agent.toml
.github/workflows/pr_agent.yml

chore(ci): add AI tool pr agent to review PR

---

.github/prompts/issue-analysis.prompt.yml
.github/prompts/reply-summary.prompt.yml
.github/workflows/issue-ai-analysis.yml

chore(ci): add AI bot to analyze issue

---

custom_components/midea_ac_lan/manifest.json
requirements.txt

chore(main): bump midea-local to v6.5.0

---

doc/A1.md

Update the doc for A1 to match the similarly named pull request on midea local as requested.

feat(a1): allow customization of default modes and speeds for dehumidifiers

---

custom_components/midea_ac_lan/manifest.json

chore(main): midea_ac_lan release v0.6.10
